#!/bin/bash

# Copyright 2016 Marko Dimjašević
#
# This file is part of Clover.
#
# Clover is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Clover is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with maline.  If not, see <http://www.gnu.org/licenses/>.


set -x

EXTRACT_DIR=$(mktemp --directory)
# HOME=/tmp/buildd by default
cd $HOME

# The following loop will work as paths in the .llvm_bc header of
# object files are absolute, hence it does not matter where we extract
# .deb archives
for DEB in $(find . -name "*.deb"); do
    dpkg --extract $DEB $EXTRACT_DIR
done

# A header consisting of first 4 bytes indicating an ELF object file
ELF_H=$(head -c 4 /usr/bin/find)

cd $EXTRACT_DIR

for f in $(find . -type f); do
    SEQ=$(head -c 4 $f)
    if [ "$SEQ" != "$ELF_H" ]; then continue; fi
    
    echo -n "Checking if $f has an llvm_bc section... "
    if [ "$(objdump -h $f | grep \.llvm_bc | wc -l)" != "0" ] ; then
        echo "yes"
	(
	    BS_NAME=$(basename $f)
	    DIR_NAME=$(dirname $f)
	    cd ${DIR_NAME}
	    extract-bc ${BS_NAME}
	    if [ $? -eq 0 ] ; then
		echo "${EXTRACT_DIR}/${DIR_NAME}/${BS_NAME}" >> $HOME/success
	    else
		echo "Unable to extract bitcode"
	    fi
	)
    else
        echo "no"
    fi
done

if [ -f $HOME/success ]; then
    cat $HOME/success
else
    echo "No successfully extracted bitcode files"
fi
