#!/bin/bash

# Copyright 2016 Marko Dimjašević
#
# This file is part of Clover.
#
# Clover is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Clover is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with maline.  If not, see <http://www.gnu.org/licenses/>.


set -x

cd /tmp/buildd
DSC_FILE=$(ls -1 *.dsc)
BS_NAME=$(basename --suffix=".dsc" ${DSC_FILE})
PKG_NAME=$(echo ${BS_NAME} | awk -F"_" '{print $1}')
RULES_PATH=$(find . -path "*/debian/rules")
DIR=$(dirname $(dirname ${RULES_PATH}))
cd $DIR

klee -libc=uclibc --posix-runtime ${PKG_NAME}.bc
