#!/bin/bash

# Copyright 2016 Marko Dimjašević
#
# This file is part of Clover.
#
# Clover is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Clover is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with maline.  If not, see <http://www.gnu.org/licenses/>.


set -x

apt-get install --yes clang-${LLVM_VERSION} llvm-${LLVM_VERSION} llvm-${LLVM_VERSION}-dev llvm-${LLVM_VERSION}-tools

cd /usr/bin
GCC_VERSION="4.9"
rm g++-$GCC_VERSION gcc-$GCC_VERSION cpp-$GCC_VERSION
ln -s clang++-${LLVM_VERSION} g++-$GCC_VERSION
ln -s clang-${LLVM_VERSION} gcc-$GCC_VERSION
ln -s clang-${LLVM_VERSION} cpp-$GCC_VERSION

echo "Block the installation of a new gcc version"
echo "gcc-${GCC_VERSION} hold" | dpkg --set-selections
echo "cpp-${GCC_VERSION} hold" | dpkg --set-selections
echo "g++-${GCC_VERSION} hold" | dpkg --set-selections
