#!/bin/bash

# Copyright 2016 Marko Dimjašević
#
# This file is part of Clover.
#
# Clover is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Clover is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with maline.  If not, see <http://www.gnu.org/licenses/>.


set -x

# Get and install STP, KLEE and their dependencies
apt-get install --yes libboost-program-options1.55.0 libgcc1 libstdc++6 minisat libcap2 libffi6 libllvm${LLVM_VERSION} libtinfo5 python python-tabulate

STP_PKG=stp_2.1.1+dfsg-1_amd64.deb
KLEE_PKG=klee_1.1.0-1_amd64.deb
wget https://dimjasevic.net/marko/klee/${STP_PKG}
wget https://dimjasevic.net/marko/klee/${KLEE_PKG}
dpkg -i ${STP_PKG}
dpkg -i ${KLEE_PKG}
rm ${STP_PKG} ${KLEE_PKG}
