#!/bin/bash

DISTRIBUTION=jessie
BASEPATH=/var/cache/pbuilder/${DISTRIBUTION}.cow

MIRRORSITE=http://debian.usu.edu/debian/

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
HOOKDIR=${SCRIPT_DIR}/hookdir

export LLVM_VERSION=3.4
export LLVM_COMPILER=clang
export LLVM_COMPILER_PATH=/usr/lib/llvm-${LLVM_VERSION}/bin
export WLLVM_DIR=/usr/bin

# dpkg-buildpackage flags
STRIP_FLAGS="-fstack-protector-strong -O2"
export DEB_CFLAGS_STRIP=${STRIP_FLAGS}
export DEB_CXXFLAGS_STRIP=${STRIP_FLAGS}
export DEB_OBJCFLAGS_STRIP=${STRIP_FLAGS}
export DEB_OBJCXXFLAGS_STRIP=${STRIP_FLAGS}

# Use WLLVM wrappers for CC and CXX
export CC=wllvm
export CXX=wllvm++

export HOME=/tmp/buildd
